### ISSUE TITLE
gridDnD & Row IDs (and onEnter/ondblClickRow)

### ISSUE THREAD

**Issue by Rikaelus** [tonytomov/jqGrid#867]
I have two jqGrids that rows can be moved back-and-forth between and also both an onEnter and ondblClickRow listener to also initiate a row move. In playing around with these functionalities, I noticed that sometimes ondblClickRow/onEnter would move multiple rows at once (even though the event is fired only once) or sometimes move the desired row and create a duplicate in the destination.

It took a while to find a way to reproduce this, but I think it can reliably done by:

1. DnD 2 rows from Grid A to Grid B
2. DnD the same two rows from Grid B back to Grid A
3. Trigger a move for either row via ondblClickRow, onEnter, or I'm guessing any other

Either both rows will be moved (with one being a duplicate) or the one you click on will move and get a duplicate at the destination.

Just in case I'm doing something wrong in my ondblClickRow/onEnter logic, this is what I'm doing for both:
```
function(rowId){
    if ( !rowId ){ return false; }   // To avoid moving the "jqgfirstrow" row
    var row = $grid1.getRowData(rowId);
    $grid2.addRowData(rowId,row,'first'); 
    $grid2.trigger('reloadGrid',{page:1}); 
    $grid1.delRowData(rowId);
}
```

Digging into the DOM I found an anomaly that is MAYBE leading to this flawed behavior. When a row is dragged and dropped into the target,  the normal ID is being replaced by "dnd_943" or similar. If I perform an event on that row, the ID is even going into its listener as that. So even if this isn't the cause of this odd duplication problem, I imagine losing the typical ID could also be problematic.

P.S. I'm thinking it might also be a bug that keyboard binding is able to focus on that "jgfirstrow" row and that the row is even recognized in event listeners.

Thanks

**Comment by tonytomov** [comment]
Hello,

Can you please show me a demo demonstrating the problem and description how to reproduce? This will save us a lot of time. You may use jsfiddle https://jsfiddle.net/ or similar for this purpose.

Thank you

**Comment by Rikaelus** [comment]
This one can demonstrate the ID changing problem, though I haven't been able to reproduce my duplication problem yet.

https://jsfiddle.net/as90Lkbo/

Just drag and drop items from one to the other then double-click on them to move them back. You'll see the ID value change to what jQuery (I think) set it to during the drag and drop operation.

**Comment by tonytomov** [comment]
To resolve currently the problem you do not need to trigger reloading within double click row. There is no need to do this - adding and deleting row data automatically refresh the grid. Not sure why this happen, but I will investigate this later.

**Comment by tonytomov** [comment]
Hello,

I see you use a old jqGrid version 4.6. 
In the  current version 5.2.1 the problem is solved when you set the key property in colModel:

```js
$(document).ready(function(){
	var $g1 = $('#jqGrid1').jqGrid({
		datatype: 'local',                  
		colNames:['ID','Text'],
    colModel:[
	    {name:'id',index:'id', key : true},
      {name:'text',index:'text'}
		],
		ondblClickRow: function(rowId){
    	if ( !rowId ){ return false; }                  
      var row = $g1.getRowData(rowId);
      $g2.addRowData(rowId,row,'first');
      $g2.trigger('reloadGrid',{page:1});
      $g1.delRowData(rowId);
      return false;
    }
  });
	var $g2 = $('#jqGrid2').jqGrid({
		datatype: 'local',                  
		colNames:['ID','Text'],
    colModel:[
	    {name:'id',index:'id', key : true},
      {name:'text',index:'text'}
		],
		ondblClickRow: function(rowId){
    	if ( !rowId ){ return false; }                  
      var row = $g2.getRowData(rowId);
      $g1.addRowData(rowId,row,'first');  
      $g1.trigger('reloadGrid',{page:1});
      $g2.delRowData(rowId);
      return false;
    }
  });
```

Kind Regards
Tony

**Comment by Rikaelus** [comment]
I'm using 5.2.1 locally. I can't find a publicly accessible instance of
that version to use in jsFiddle. I made sure to have "key:true" on all my
primary key fields, but the problem is still persisting that the row's ID
attribute is being reset to "dnd_###". In my local instance it's not as
obvious as changing the presented value in the table, but inspecting the
DOM shows the different ID attribute value.

As a side note...
Isn't it dangerous to DOM integrity to put table values in the ID field?
The values of ID fields are supposed to be unique on a given page, but
populating them based on arbitrary data could result in duplication across
multiple grids or even conflicts with explicitly defined DOM IDs. Worst
case, an assigned ID could apply unintended CSS styling or Javascript
functionality to the TR. If the key value of the row needs to be easily
referenced, it seems that making it "data-id" or prepending the table's ID
to the current value would help ensure uniqueness.

**Comment by Rikaelus** [comment]
I may have pinned down a solution to this.
Looking back at the documentation, the dnd_### doesn't look like an anomaly so much as expected behavior with the "autoid" default setting.

If I do this:
`autoid: function(d){ return d['id']; }`
... then the proper ID value is retained through all DnD moving. What's more, this seems to have fixed the duplication problem and multiple-rows-moving problem, seemingly confirming my suspicion that the ID behavior was the cause of those problems.

I'll be continuing to test this.

**Comment by tonytomov** [comment]
Please consider reopen if you find it is not working as expected
