### ISSUE TITLE
Incorrect handling of mouse clicks in jqModal.js

### ISSUE THREAD

**Issue by snobo** [tonytomov/jqGrid#873]
After many years of using jqGrid, I have stumbled upon a major flaw of jqModal.js. Apparently it captures and prevents mousedown events outside of a popup window; and it works fine until I attach jQuery Datepicker for single field search via searchoptions.dataInit(). In that case I observe interesting but obviously nasty effect: while selecting days in the calendar is still possible, selecting in Datepicker's month and year drop-downs becomes not possible _as soon as the SELECT's OPTION clicked appears to be outside of search popup window_. 

E.g. selecting January and February in this case is still possible, but March-December is not:
![options_outside_window](https://user-images.githubusercontent.com/1439713/28572591-59afcb44-7150-11e7-9943-1b7f6e8b0a0a.png)

**The bug occurs in Firefox (all platforms) and in IE/Edge (all versions)**. It works well in Chrome, Safari and Opera on all platforms though.

**Comment by tonytomov** [comment]
Hello,
Thank you for posting. Will try to reproduce the problem and in case if it can't be reproduced from me I will ask for a demo

**Comment by tonytomov** [comment]
Hello,

Confirm the problem. Just to note that it appear only when the modal: true is set for the search dialog

**Comment by snobo** [comment]
Hello, 
yes of course, because that's when jqModal.js kicks in trying to establish the modality of popups. But I think the modal windows are preferable, so imo this setting should not be set to false...

**Comment by tonytomov** [comment]
It is funny - according to this commit: https://github.com/tonytomov/jqGrid/commit/3cdc40c2fb3349f7650cfc22fe0fe07fea098cc7 the problem should be fixed. See here:  https://stackoverflow.com/questions/12270509/datepicker-options-changemonth-and-changeyear-not-working-in-jqgrids-edit-f

**Comment by snobo** [comment]
But if I grab jqModal.js from https://github.com/tonytomov/jqGrid/raw/3cdc40c2fb3349f7650cfc22fe0fe07fea098cc7/js/jqModal.js, the problem still persists.

**Comment by tonytomov** [comment]
Yes it persist in my version too. My question to myself is why and it seems that the fix applied  is not correct. I have some good results for now, but let me see more

**Comment by tonytomov** [comment]
The only sensible fix that I see for now is to enlarge the height and width offset of the mousedown in case a component is outside the modal. See this fix: https://github.com/tonytomov/jqGrid/commit/827fec2e856b7977c44af8e2e88f921857b872e1. for now this should work. Later I will add these parameters to be configured by the user. 

Please, let me know if the fix is working for you. For now there may be a problem with the last year selection, but it will be avoided when set these as parameter to the search dialog

**Comment by snobo** [comment]
Honestly, I can't see it as a sensible fix. Increasing the offset is only allowing some more OPTIONs to be clicked, but not necessarily all - as the Year drop-down can contain many years and therefore stick out from the popup significantly. Tried it in my applications - and immediately witnessed it. 

I'm afraid the whole approach is not valid and the modalness should be ensured in some other way (maybe a-la jQuery UI?).

**Comment by tonytomov** [comment]
Thank you. Will try to find better solution.

**Comment by tonytomov** [comment]
Could you please test it after this change: https://github.com/tonytomov/jqGrid/commit/112f4f268b441a691fb88b03dee972055cb633a2 it is working as expected. If yes, please close the issue.

Thank you 

Kind Regards

**Comment by snobo** [comment]
well, still not completely fixed. It now works well when a calendar opens normally _below_ the popup. But when a popup is located nearby the lower screen border, so there is no room for the calendar there and it is drawn _above_ the popup, I cannot even open the year/month drop-downs at all...
![dropdown-up](https://user-images.githubusercontent.com/1439713/29406884-2702f77c-834b-11e7-9beb-ef5d2ceac53d.png)

**Comment by tonytomov** [comment]
@snobo 

Thanks for this. 
The situation you describe can't be fixed with the current code of jqModal, because of its nature. 
Currently we are working on alternative solution,  which will not impact current users, but will solve the problems you describe.


I will let you know abut this in the next days.

Thank you very much for your investigations and help us to make our plug-in better.

Regards
Tony

**Comment by tonytomov** [comment]
Hello,

I have fixed the search dialog not to use jqModal, but keep the functionality.

Here is the fix: https://github.com/tonytomov/jqGrid/commit/df895d7c65b771db61e77285c43074650762095a 

Actually what you need to do is to disable the jqModal - setting this property to false in search options.
When using the build, do not forget to update the css too.

Please let me know if the problem is fixed for you.

Kind Regards,
Tony

**Comment by snobo** [comment]
Unfortunately it's very hard for me to test this fix, as it's in grid.common.js which is not compatible with the 4.x branch my applications are still on. I'm considering an upgrade but as I have so many tweaks and my own integrations that seem to be tightly related to the 4.x code it doesn't look to be quick and easy...

**Comment by tonytomov** [comment]
I will close the issue. If you think it is not a good fix, please reopen it.
